// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEi0bLJQPQf1TPBlHGdNXBg9QnLyRPQ5I',
    appId: '1:552062917643:web:bad6f66560199a68c3fb0e',
    messagingSenderId: '552062917643',
    projectId: 'umunc-v',
    authDomain: 'umunc-v.firebaseapp.com',
    storageBucket: 'umunc-v.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQZbcHO3xYcA9butJ7EmKCSIYTw7N5LaI',
    appId: '1:552062917643:android:657f090c78dc14eec3fb0e',
    messagingSenderId: '552062917643',
    projectId: 'umunc-v',
    storageBucket: 'umunc-v.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxM-SwhZ42Q6qyDCZVfMiPzULTWwDpR9s',
    appId: '1:552062917643:ios:e4e03e2c129a3499c3fb0e',
    messagingSenderId: '552062917643',
    projectId: 'umunc-v',
    storageBucket: 'umunc-v.appspot.com',
    iosClientId: '552062917643-47kjlil0f6dpditlhff78gpopa2e1s4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjectIdeas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxM-SwhZ42Q6qyDCZVfMiPzULTWwDpR9s',
    appId: '1:552062917643:ios:e6b1c3a7ab8291f1c3fb0e',
    messagingSenderId: '552062917643',
    projectId: 'umunc-v',
    storageBucket: 'umunc-v.appspot.com',
    iosClientId: '552062917643-k5nakf182agvjngf4fqboft8ud0g4deh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjectIdeas.RunnerTests',
  );
}
